on:
  pull_request:
    paths:
      - 'changed-files/action.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files
        id: changed-files
        uses: ./changed-files

      - name: Check changed files output
        run: |
          changed_files="${{ steps.changed-files.outputs.changed-files }}"
          expected_file="changed-files/action.yml"

          if [[ $changed_files =~ $expected_file ]]; then
            echo "$expected_file found in changed files"
          else
            echo "$expected_file not found in changed files"
            exit 1
          fi
